# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
