# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_auto_20160727_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('serial', models.PositiveIntegerField(default=2016072701)),
                ('expire', models.PositiveIntegerField(default=1)),
                ('retry', models.PositiveIntegerField(default=2)),
                ('refresh', models.PositiveIntegerField(default=3)),
                ('minimum', models.PositiveIntegerField(default=4)),
            ],
            options={
                'db_table': 'soa',
            },
        ),
    ]
