# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_soa'),
    ]

    operations = [
        migrations.AddField(
            model_name='soa',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dns.Line'),
            preserve_default=False,
        ),
    ]
