# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0006_soa_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soa',
            name='line',
        ),
        migrations.AddField(
            model_name='soa',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soa', to='dns.Domain'),
            preserve_default=False,
        ),
    ]
