# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0007_auto_20160727_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='NS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns', to='dns.Domain')),
            ],
            options={
                'db_table': 'ns',
            },
        ),
    ]
